### ISSUE TITLE
Best Practice Using scTensor for large 10x Genomics datasets

### ISSUE THREAD

**Issue by AMA111** [rikenbit/scTensor#1]
Dear Developers,

Recently, I have been reading your scTensor pre-print paper which looks interesting and I would like to have your opinion regarding using it for complex tumor microenvironment project ~ 20 main cell types (290,00 cells from 10x genomics SC RNA-seq). I have a Seurat object which would be the start point with the cell type annotations. Your suggestions would be helpful. 

Best wishes,
Abdelrahman

**Comment by kokitsuyuzaki** [comment]
Hi, @AMA111 

Ok, I will create another document (vignette) for the analysis of Seurat object.
Since the matrix of Seurat is formatted as a sparse matrix,
Perhaps, I have to modify the source code of scTensor.

Koki

**Comment by Yale73** [comment]
@AMA111 Hi, Koki, I also want to use scTensor to for integrated Seurat object with 13 cell types. After I followed the vignette in the Webpage, I realized one thing: how can I use the seurat cell cluster and t-sne after change my data to matrix with geneID? As when I transfer the gene symbol to geneID, they moved some genes because of unrecognization, then it will not match my original cluster. Have you ran this issue? How do you fix this? Can you share your code to me?
 Many thanks!
Yale Liu

**Comment by kokitsuyuzaki** [comment]
I think the cluster label won't change, even if the gene identifiers are changed (e.g. Symbol → NCBI Gene ID), and there is no problem.

**Comment by Yale73** [comment]
@kokitsuyuzaki Yeah, you are right. One is row, and another is column. Thanks!
