### ISSUE TITLE
Running cellCellDecomp on multiple cores

### ISSUE THREAD

**Issue by michelesilvestro** [rikenbit/scTensor#13]
Hi Koki,
thank you very much for developing scTensor, it's extremely interesting and a powerful tool.

There is a way to run scTensor (specifically the function cellCellDecomp) on multiple CPU cores?

Thanks
Michele

**Comment by kokitsuyuzaki** [comment]
Hi,Michele

Thank you for your interest in my tools.
Yes, I'm now working on speeding up the calculation and reducing the amount of memory used, and I'm trying to deal with it by devising the data format (e.g., sparse matrix format) rather than parallelizing it.

Please wait for the future version of scTensor.

Regards,

Koki

**Comment by michelesilvestro** [comment]
Ok thank you very much.
I am looking forward to future versions of scTensor.
