### ISSUE TITLE
ligand recptor activity score

### ISSUE THREAD

**Issue by MichaelPeibo** [rikenbit/scTensor#14]
Hi scTensor team,

Very inspring package!

I wonder, if there is some metric for shwoing a cell ligand-receptor activity.
I guess it is quite complicated in real life, since it is hard to determine a so called 'ligand-receptor activity'.
My first thought is to use 'AddModuleScore' function calculating certain  ligand-receptor pair of interest in Seurat, while I cannot give a proper explaination of for negative value of a ligand-receptor pair. see [this ](https://github.com/satijalab/seurat/issues/522)

Any suggestion if I can catch something like what I described from scTensor?

Apoligize if this is off-topic.

**Comment by kokitsuyuzaki** [comment]
Hi,

In the analysis of coexpression of ligand and receptor, such an information is used for the detection of cell-cell interaction.
That's why the scores are assigned to all the combination of cells, not single cells.

Suppose that the high/low expression of ligand/receptor as follows:

	- L+ : High expression of ligand
	- L- : Low expression of ligand
	- R+ : High expression of receptor
	- R- : Low expression of receptor

, only L+ vs R+ pattern does make sense.

Some ad hoc scoring strategies for cell-cell interaction are proposed.
https://academic.oup.com/nar/advance-article/doi/10.1093/nar/gkaa183/5810485

Koki
