### ISSUE TITLE
cannot allocate vector of size 189.6 Gb

### ISSUE THREAD

**Issue by zhumengyan** [rikenbit/scTensor#7]
Thanks for your great software.
I have tried to use scTensor on my 10X data. And my data is 17533(genes) X 14629(cells).
`
cellCellDecomp(dat, ranks=c(2,3,4))
`

But scTensor needs too many memory.
So could you provide me some suggestions on large 10X data analysis?

**Comment by kokitsuyuzaki** [comment]
Because 10X data matrix loaded by Seurat is described as a "sparse" matrix,
I'm going to implement a sparse version of scTensor soon,
but as an alternative solution, could you reduce the number of genes of the data matrix by some feature gene selection methods such as highly variable genes?

Besides, could you tell me the version of R and scTensor?
The recent algorithm in scTensor is slightly changed as a different model,
and it might be slow.

Koki
